name: Code Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Prettier
        run: npm install --global prettier

      - name: Format HTML files
        run: prettier --write "**/*.html"

      - name: Format CSS files
        run: prettier --write "**/*.css"

      - name: Format JavaScript files
        run: prettier --write "**/*.js"
